name: ci_linux

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - ".github/workflows/linux_ci.yml"
  pull_request:
    paths:
      - "**.h"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - ".github/workflows/linux_ci.yml"
jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup build
      env:
        CC: gcc
    - run: git submodule update --init --recursive
    - run: meson build
    - run: ninja -C build
    - run: ninja -C build test
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
